repos:
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint src/churn_library.py
          language: system
          always_run: true
          pass_filenames: false